### ISSUE TITLE
Crossfade not updating with Sonos Move

### ISSUE THREAD

**Issue by montecas** [jeremywillans/sonos-crossfade#1]
Trying to update crossfade status results in the following:

![image](https://user-images.githubusercontent.com/76979346/103594557-038d9180-4ec7-11eb-8690-7346dac2c3e7.png)

**Comment by jeremywillans** [comment]
This happens if your trying to change it for an unsupported state (radio station, tv input, etc). If you attempt to make the same change in the app, the option should be greyed out. 

I’ll see if I can add some error handling to prevent this error

**Comment by jeremywillans** [comment]
Closing this. As I will be archiving this repo as the base functionality will be moved into Core HA
